name: 's_track'
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_animate: ^4.5.0
  device_preview: ^1.0.0
  cupertino_icons: ^1.0.3
  flutter_settings_ui: ^3.0.1
  flutter_svg: ^2.0.0
  curved_navigation_bar: ^1.0.3
  carousel_slider: ^4.0.0
  smooth_page_indicator: ^1.0.0
  flutter_screenutil: ^5.6.0
  http: ^1.2.2 # For making HTTP requests
  shared_preferences: ^2.0.0 # For storing simple key-value data
  url_launcher: ^6.0.0 # For launching URLs
  firebase_core: ^3.3.0 # Firebase core package
  firebase_auth: ^5.1.3 # Firebase authentication
  cloud_firestore: ^5.2.0 # Firestore for cloud database
  google_sign_in: ^6.2.1 # Google Sign-In
  flutter_local_notifications: ^17.2.1+2 # For local notifications
  flutter_pdfview: ^1.2.7
  dio: ^5.0.10
  permission_handler: ^10.2.0
  open_file: ^3.2.1
  flutter_downloader: ^1.7.11
  intl: ^0.19.0
  lottie: ^1.2.2
  sliding_up_panel: ^2.0.0+1
  animations: ^2.0.5
  percent_indicator: ^4.2.2
  fluttertoast: ^8.0.9
  provider: ^6.1.2
  salomon_bottom_bar: ^3.3.1
  convex_bottom_bar: ^3.0.0
  persistent_bottom_nav_bar: ^5.0.2
  bottom_navy_bar: ^6.1.0






dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/vm0.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo/vm0.png"
    background_color: "#FF5733" # Replace with your desired background color
    theme_color: "#C70039" # Replace with your desired theme color
  windows:
    generate: true
    image_path: "assets/logo/vm0.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/vm0.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo/
    - assets/products/
    - assets/product/
